### PR TITLE
Feature/drop 28/Account-Creation-form added 

### PR DESCRIPTION
**Pull request by Natalia2311**
## Describe your changes
Account Creation Form was created which is the first step of the registration workflow.
## Issue ticket number and link
https://tripleten-apiary.atlassian.net/browse/DROP-28
## Checklist before requesting a review

- [ x] I have performed a self-review of my code
- [ ] If there are changes to components, I have added / updated automated tests
- [x ] I have made any necessary updates to Storybook to accompany these changes
- x[ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

### CODE REVIEW

**Review by dani9401 — APPROVED** [review]
Great job! Looks good to me :)

**Comment by dani9401** [comment]
@Natalia2311 Hey! One thing I just noticed...

Your branch is behind main right now (Josh merged a couple tickets into main I believe last week). 
So before you push this into final code review, update your branch with the new code, make sure it doesn't break anything on your new form, and then it should be good to have Josh do a final code review!

**Comment by Natalia2311** [comment]
@dani9401. Thank you for review. The code was updated.

**Comment by dani9401** [comment]
Hey! Here's what I'm still seeing. 

image
image

**Pull request closed without merging**
