### PR TITLE
feat: universal modal component

### PR DESCRIPTION
**Pull request by Lausonsiyo**
## Describe your changes
An universal model component has been created with: 

storybook examples

ModelContext  for tracking modal state

useModal hook that provides functions for opening and closing a modal as well as an isOpen value

Only one modal may be open at a time

The modal its animated on open and close, it appears to slide up from the bottom of the screen like a drawer
## Checklist before requesting a review

- [ ] I have performed a self-review of my code
- [ ] If there are changes to components, I have added / updated automated tests
- [ ] I have made any necessary updates to Storybook to accompany these changes
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

### CODE REVIEW

**Comment by dani9401** [comment]
@Lausonsiyo Hey! Is it possible to put the hook, provider, and context all inside the model.ts file instead of having all separate files for each? I don't believe this a requirement on the ticket, just something I noticed that I hadn't seen setup wise before.

I am new to storybook, but I'm not able to get the modal to behave like expected. I attached a video. Is this what you're seeing as well? 

https://github.com/user-attachments/assets/cbb6969d-4537-4664-9ae6-7ace29d19d0b

**Comment by Lausonsiyo** [comment]
@dani9401 Hey I applied the comments the best i can so, I refactor the modal component and got the provider, and context all inside the model.ts file, I tried to make the hook but eslint complaints that I declared but i was not using it,
fix the UI for small screens devices
feature an action for the button itself, if you have any other recommendations or any advice let me know

**Comment by dani9401** [comment]
@Lausonsiyo This looks cleaner now and thank you for the helpful video in Storybook. I believe this passes all the criteria on the Jira ticket. I'm also new to Storybook too so I'll be eager to see what Josh says about this ticket. Marking this as approved :)

**Review by dani9401 — APPROVED** [review]

**Review by jahorwitz — APPROVED** [review]
I made a few changes to the way we handle the modal state to make it a little easier to work with:

[commit](https://github.com/jahorwitz/drops/pull/21/commits/d87d8cf07b798312c28bb241c7fe684bf56f46bd)

**Pull request merged**
