### PR TITLE
Feature/time setter

### PR DESCRIPTION
**Pull request by maryafzali24**
## Issue ticket number and link
Drop-7 
https://tripleten-apiary.atlassian.net/jira/software/projects/DROP/boards/5?selectedIssue=DROP-7

## Checklist before requesting a review

- [ #] I have performed a self-review of my code
- [ ] If there are changes to components, I have added / updated automated tests
- [ ] I have made any necessary updates to Storybook to accompany these changes
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ #] My changes generate no new warnings

### CODE REVIEW

**Review by Dillona25 — CHANGES_REQUESTED** [review]
The styles and everything look great! I would perhaps make a dropdown or a ```selection``` element for the last block so users can only pick AM or PM. Currently they can type anything into that block

**Review by cgenardini — COMMENTED** [review]
Good job on the refactor! A few notes
- enter anything in the 'AM/PM' column it fills in all three boxes with the characters. 
- There is no error feedback if I submit the form with nothing or invalid number or character. (I would suggest copying the button the textInput storybook form to test)
- A placeholder time and AM or PM would be helpful.
- I don't know if this is in the parameters but I am able to enter letters and numbers in all fields and more that 2 characters in each field.

**Review by cgenardini — COMMENTED** [review]
Looking great! Just a couple notes:
- Remove console.log
- Fix Error in console: Warning: forwardRef render functions accept exactly two parameters: props and ref. Did you forget to use the ref parameter?
- Add: required and validator to ...register. You can use a regex to test the value of the input. This should trigger the error message when a user tries to submit an empty or incomplete form. Right now there is no error when submitting the incomplete form.

**Comment by maryafzali24** [comment]
> Looking great! Just a couple notes:
> 
> * Remove console.log
> * Fix Error in console: Warning: forwardRef render functions accept exactly two parameters: props and ref. Did you forget to use the ref parameter?
> * Add: required and validator to ...register. You can use a regex to test the value of the input. This should trigger the error message when a user tries to submit an empty or incomplete form. Right now there is no error when submitting the incomplete form.

- I added validation and error message to ...register. 

- No, I didnt forget. For forwardRef render functions When I was try to  commit out the code, I got eslint error "ref is defined but never used". That is why I get rid of it.

**Review by cgenardini — COMMENTED** [review]
Changes look great! Good job on the component. Go ahead and move to final review.

**Review by jahorwitz — APPROVED** [review]

**Pull request merged**
